-- to be executed as groupics_test user

-- snippet table
CREATE TABLE public.snippet
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title character varying(100) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    created TIMESTAMPTZ NOT NULL,
    expires TIMESTAMPTZ NOT NULL,
    CONSTRAINT snippet_pkey PRIMARY KEY (id)
)
TABLESPACE pg_default;

-- user table
CREATE TABLE public.user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name VARCHAR(255) COLLATE pg_catalog."default" NOT NULL,
	email VARCHAR(255) COLLATE pg_catalog."default" UNIQUE NOT NULL,
	hashed_password CHAR(60) NOT NULL,
    created TIMESTAMPTZ NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT user_pkey PRIMARY KEY (id)
)
TABLESPACE pg_default;

INSERT INTO public.user (name, email, hashed_password, created) VALUES (
    'Alice Jones',
    'alice@example.com',
    '$2a$12$NuTjWXm3KKntReFwyBVHyuf/to.HEwTy.eS206TNfkGfr6HzGJSWG',
    '2020-10-01 10:50:00'
);
