-- database
CREATE DATABASE groupics;

-- user
CREATE USER groupics WITH ENCRYPTED PASSWORD '';

GRANT ALL PRIVILEGES ON DATABASE groupics TO groupics;

-- switch to database
\c groupics

-- snippet table
CREATE TABLE public.snippet
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title character varying(100) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    created timestamp without time zone NOT NULL,
    expires timestamp without time zone NOT NULL,
    CONSTRAINT snippet_pkey PRIMARY KEY (id)
)
TABLESPACE pg_default;

GRANT ALL ON TABLE public.snippet TO groupics;
