-- database
CREATE DATABASE groupics;

-- user
CREATE USER groupics WITH ENCRYPTED PASSWORD '';

GRANT ALL PRIVILEGES ON DATABASE groupics TO groupics;

-- switch to database
\c groupics

-- snippet table
-- DROP TABLE public.snippet;
CREATE TABLE public.snippet
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title character varying(100) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    created timestamp without time zone NOT NULL,
    expires timestamp without time zone NOT NULL,
    CONSTRAINT snippet_pkey PRIMARY KEY (id)
)
TABLESPACE pg_default;

ALTER TABLE public.snippet
    OWNER to groupics;


-- user table
-- DROP TABLE public.user;
CREATE TABLE public.user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name VARCHAR(255) COLLATE pg_catalog."default" NOT NULL,
	email VARCHAR(255) COLLATE pg_catalog."default" UNIQUE NOT NULL,
	hashed_password CHAR(60) NOT NULL,
    created TIMESTAMP NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT user_pkey PRIMARY KEY (id)
)
TABLESPACE pg_default;

ALTER TABLE public.user
    OWNER to groupics;
